name: 'bashmu-action'
description: 'cache + queued-build-hook + nix-eval-jobs / mini hydra'

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'node20'
  main: 'dist/index.js'
